GH-746 Replace commit message check action with simple script

diff --git a/.github/workflows/check-commit-messages.yml b/.github/workflows/check-commit-messages.yml
--- a/.github/workflows/check-commit-messages.yml
+++ b/.github/workflows/check-commit-messages.yml
@@ -5,9 +5,6 @@ on:
       - opened
       - reopened
       - synchronize
-  push:
-    branches:
-      - main
 
 permissions:
   contents: read
@@ -17,14 +14,25 @@ jobs:
   check-commit-message:
     name: Check Commit Message
     runs-on: self-hosted
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      REPOSITORY: ${{ github.repository }}
+      PR_NUMBER: ${{ github.event.pull_request.number }}
     steps:
       - name: Check for referenced issue
-        uses: gsactions/commit-message-checker@v2
-        with:
-          pattern: '^((\#|GH\-|gh\-)[0-9]+|NOISSUE|Merge|Revert).+'
-          flags: 'gm'
-          error: 'Commit message must reference an issue at the start, start with NOISSUE, or start with Merge'
-          excludeDescription: 'true' # exclude description and title of pull request
-          excludeTitle: 'true'
-          checkAllCommitMessages: 'true'
-          accessToken: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          url="https://api.github.com/repos/$REPOSITORY/pulls/$PR_NUMBER/commits"
+          commits=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$url" | jq -r '.[].commit.message')
+          regex="^((#|GH-|gh-)[0-9]+|NOISSUE|Merge|Revert).+"
+          
+          echo "Checking commit messages against \"$regex\"..."
+          
+          commits=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$url" | jq -r '.[].commit.message')
+          invalid=$(echo "$commits" | grep -vE $regex || true)
+          
+          if [[ -n "$invalid" ]]; then
+            echo "$invalid" | sed 's/^/❌  /'
+            exit 1
+          fi
+          
+          echo "✅ All commit messages are valid."
